### ISSUE TITLE
Can't make netbsd-native sandbox on default evbarm-earmv7hf (Raspberry Pi) install

### ISSUE THREAD

**Issue by truist** [jmmv/sandboxctl#4]
I just worked through http://julio.meroh.net/2017/02/pkg_comp-2.0-tutorial-netbsd.html on a new RPi with NetBSD 7.1, and ran into an issue trying to create a "native" sandbox - it errored out trying to copy `/netbsd` into the sandbox, because that file isn't there. 

As near as I can tell, this platform puts the kernel in `/boot/kernel7.img`, rather than in `/netbsd`.

I looked at the sources for `sandboxctl` and it looks like the netbsd-native platform is hard-coded to expect `/netbsd` so for now I just symlinked it there, and that seems to work. I'm a little worried about it causing other issues, but so far (and across reboots) it seems fine.

**Comment by jmmv** [comment]
I was going to change the code to recognize a `/boot` directory and to ignore `/netbsd` if not present... but then I went on checking the release sets from here:

ftp://ftp.netbsd.org/pub/NetBSD/NetBSD-7.1/evbarm-earmv7hf/binary/sets/

and found that all `kern-*.tgz` sets unpack a `/netbsd` file, and that the `base.tgz` set does not create a `/boot` directory.

So I'm wondering: how did you set up your system? It seems that following the "normal" NetBSD installation procedure of using the release sets should result in `/netbsd` being created.

I know that the usefulness of `/netbsd` depends on the loader though... For example, I do have a macppc installation where the `/netbsd` file is not used because the boot loader has to use a file from a dedicated HFS partition. However, the NetBSD installer did unpack a `kern-*.tgz` set which resulted in `/netbsd` being created. That file is not really used during the system boot, but it's probably expected by some tools/packages to be there.

I can change `netbsd-native` to ignore `/netbsd` and recognize `/boot`... but then I'm wondering what to do with `netbsd-release` because this will result in inconsistencies: `netbsd-native` may skip `/netbsd` in some cases silently, but `netbsd-release` will always create it. And doing the former means that maybe some utility that expects the kernel in the standard location will fail.

Thoughts?

**Comment by truist** [comment]
I followed the instructions at <https://wiki.netbsd.org/ports/evbarm/raspberry_pi/> and used the pre-configured `armv7.img` image. (So I got whatever the person who configured the image thinks I should have gotten - I don't know how they arrived where they did.)

I'm pretty sure it's that way on the Pi because the `/boot` partition is `msdos`, and has to be that way, so the kernel must necessarily be in there. Maybe they just deleted `/netbsd` to make it clear that if you built your own, you shouldn't just put it at `/netbsd`.

I'd be worried about any tool that **did** use `/netbsd` when that file wasn't the actual running kernel - what if it didn't match the one in `/boot`? 

On the other hand, how do you tell which file in `/boot` has the kernel? On the Pi it is `/boot/kernel7.img`; presumably that isn't a standard name? It looks like `/boot/start.elf` references that name, but I have no idea if that's helpful.

Or maybe you don't have to have the individual kernel, you just need the whole partition? I don't know enough about this stuff to be helpful, sorry.

In any case, my vote is to teach the sandbox to recognize `/boot` (so you are referencing the actual active kernel), if you know what you should do in that case.

**Comment by jmmv** [comment]
Bleh, what I said about macppc is incorrect: the kernel does not live in a separate partition... but I have memories of using other ports in which this was the case. I'm probably getting confused with mac68k.

I'd say that the RPI image you got is bogus, and that the process to generate it deserves reporting a bug. I think the image should be changed to include a `/netbsd` symlink to `/boot/kernel7.img`. Note that `hier(7)` documents `/netbsd` as the kernel executable and I'd expect tools out there to make this assumption. (sysbuild does, for example... but that's my own code too so not a valid point).

That said, I'll change the code to cope with `/boot`. Even if the host system is not "properly configured", it shouldn't be sandboxctl's business to "fix it".
